/home/hanzalt/Arduino_Programming/pythonCode/smartSystem.py:9: DeprecationWarning: Callback API version 1 is deprecated, update to latest version
  client = mqtt.Client(mqtt.CallbackAPIVersion.VERSION1)
/home/hanzalt/Arduino_Programming/pythonCode/smartSystem.py:24: RuntimeWarning: This channel is already in use, continuing anyway.  Use GPIO.setwarnings(False) to disable warnings.
  GPIO.setup(pinRelay, GPIO.OUT)
/home/hanzalt/Arduino_Programming/pythonCode/smartSystem.py:25: RuntimeWarning: This channel is already in use, continuing anyway.  Use GPIO.setwarnings(False) to disable warnings.
  GPIO.setup(pinSafe, GPIO.OUT)
18
42
960
9
2
750
17
44
960
9
2
740
16
46
960
9
2
730
16
46
960
9
2
740
16
47
960
9
2
730
16
47
960
9
2
720
16
47
960
9
2
720
16
48
960
9
2
740
16
48
960
9
2
730
16
48
960
9
2
730
16
48
960
9
2
720
16
48
960
9
2
710
16
48
960
9
2
710
16
48
960
9
2
700
16
48
960
9
2
700
16
48
960
9
2
690
15
48
960
9
2
690
15
48
960
9
2
680
15
48
960
9
2
680
15
48
960
9
2
680
16
49
960
9
2
680
17
45
960
9
2
700
18
44
960
9
2
720
18
43
960
9
2
730
18
43
960
9
2
740
18
42
960
9
2
740
18
42
960
9
2
740
18
42
960
9
2
740
18
42
960
9
2
750
17
45
960
9
2
750
16
46
960
9
2
750
16
47
960
9
2
730
16
48
960
9
2
730
16
48
960
9
2
730
16
48
960
9
2
720
16
48
960
9
2
720
16
48
960
9
2
710
16
48
960
9
2
710
16
48
960
9
2
710
16
49
960
9
2
700
16
49
960
9
2
690
16
49
960
9
2
690
15
49
960
9
2
690
15
49
960
9
2
690
15
49
960
9
2
680
15
49
960
9
2
680
15
49
960
9
2
670
15
49
960
9
2
670
15
49
960
8
2
670
Traceback (most recent call last):
  File "/home/hanzalt/Arduino_Programming/pythonCode/smartSystem.py", line 53, in <module>
    client.connect(SERVER, 1883, 60)
  File "/usr/local/lib/python3.9/dist-packages/paho/mqtt/client.py", line 1429, in connect
    return self.reconnect()
  File "/usr/local/lib/python3.9/dist-packages/paho/mqtt/client.py", line 1592, in reconnect
    self._sock = self._create_socket()
  File "/usr/local/lib/python3.9/dist-packages/paho/mqtt/client.py", line 4598, in _create_socket
    sock = self._create_socket_connection()
  File "/usr/local/lib/python3.9/dist-packages/paho/mqtt/client.py", line 4623, in _create_socket_connection
    return socket.create_connection(addr, timeout=self._connect_timeout, source_address=source)
  File "/usr/lib/python3.9/socket.py", line 843, in create_connection
    raise err
  File "/usr/lib/python3.9/socket.py", line 831, in create_connection
    sock.connect(sa)
OSError: [Errno 101] Network is unreachable
